Update codeql.yml

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -52,15 +52,13 @@ jobs:
     - name: Perform CodeQL Analysis
       uses: github/codeql-action/analyze@v3
       with:
-        category: "/language:${{ matrix.language }}-${{ github.run_id }}"
         output: ${{ matrix.language }}.sarif
 
-    - name: Debug List SARIF file
-      run: ls -la ./*javascript-typescript.sarif* || echo "SARIF file not found"
+    - name: Debug: List SARIF file
+      run: ls -la ./${{ matrix.language }}.sarif || echo "SARIF file not found"
 
     - name: Upload SARIF file
       uses: github/codeql-action/upload-sarif@v3
       with:
         sarif_file: ${{ matrix.language }}.sarif
-        category: "/language:${{ matrix.language }}-${{ github.run_id }}"
         wait-for-processing: true
